### ISSUE TITLE
renew_pid.log not found

### ISSUE THREAD

**Issue by LuoPeng-CV** [ahangchen/TrackViz#1]
Hello,when I run the ctrl/transform.py, I got a problem that"IOError: [Errno 2] No such file or directory: 'data/market_grid-cv0-train/renew_pid.log' ",and I just don't know where and how can I generate the file renew_pid.log.It's great if you can give some suggestions about this,thank you.

**Comment by ahangchen** [comment]
Have you cloned the rank-reid repository? You need it(a keras based image classifier) to generate rank results(that renew_pid.log). Make sure you have specified the proper path in the code as [this instruction](https://github.com/ahangchen/TFusion). By the way, it's not `transform.py`. It's `transfer.py`.

**Comment by LuoPeng-CV** [comment]
Thanks for your answer, I'll have a try.

**Comment by qqzhao93** [comment]
`我也遇到了同样的问题，运行transfer.py的时候，断点调试os.system(‘...’)的返回值是256，就是没有正确运行里边的代码
os.system('/home/ubuntu/anaconda2/bin/python /home/ubuntu/coding/rank-reid/rank_reid.py 0 '
              + source + ' ' + target + ' '
              + vision_train_rank_pids_path + ' '
              + vision_train_rank_scores_path + ' '
              + vision_test_rank_pids_path + ' '
              + vision_test_rank_scores_path)### 
另外rank-reid.py的sys.argv[]只有一个参数，所以opt = sys.argv[1]报错
  File "/home/ubuntu/coding/rank-reid/rank_reid.py", line 80, in <module>
    opt = sys.argv[1]

IndexError: list index out of range
希望能够得到你的帮助，谢谢

**Comment by ahangchen** [comment]
@qqzhao93 Do you mean that when you run transfer.py, you face os.system return 256 with this error stack ?

```
File "/home/ubuntu/coding/rank-reid/rank_reid.py", line 80, in 
opt = sys.argv[1]

IndexError: list index out of range
```

If you did run transfer.py, 

```python
os.system('/home/ubuntu/anaconda2/bin/python /home/ubuntu/coding/rank-reid/rank_reid.py 0 '
+ source + ' ' + target + ' '
+ vision_train_rank_pids_path + ' '
+ vision_train_rank_scores_path + ' '
+ vision_test_rank_pids_path + ' '
+ vision_test_rank_scores_path)
```

would set sys.argv[1] as 0.

rank_reid.py should be run with right arguments.

**Comment by qqzhao93** [comment]
首先，非常感谢您的及时解答!
我的意思是当我运行 run trasfer.py, 报错如下:
    raise IOError("%s not found." % path)
IOError: data/cuhk_market-train/renew_ac.log not found.

我尝试在 rank_reid.py中把原来的参数 opt =sys.argv[1] 改为sys.argv[1]=0, 没有报错.也没有文件生成。 然后当我再次运行transfer.py时候，还是之前的错误
>>
IOError: data/cuhk_market-train/renew_ac.log not found.
个人认为是下面这部分并没有成功运行rank_reid.py
os.system('/home/ubuntu/anaconda2/bin/python /home/ubuntu/coding/rank-reid/rank_reid.py 0 '
              + source + ' ' + target + ' '
              + vision_train_rank_pids_path + ' '
              + vision_train_rank_scores_path + ' '
              + vision_test_rank_pids_path + ' '
              + vision_test_rank_scores_path)
所以我想知道是否有那个位置需要特别注意和修改，谢谢！
So I want to  know that  is anywhere exits that needed changed or focus on.

**Comment by ahangchen** [comment]
`sys.argv[1]=0` is a wrong operation. You shouldn't change argv in the file executed, so revert this first.

Then, when you face
```
raise IOError("%s not found." % path)
IOError: data/cuhk_market-train/renew_ac.log not found.
```

this actually means rank_reid.py failed to generate `renew_ac.log`.

`renew_ac.log` is vision similarity as described in [TFusion](https://github.com/ahangchen/TFusion), so there must be some mistakes about the vision classifier.

One of the most possible causes is, you haven't got the cuhk pretrained model as instructed [here](https://github.com/ahangchen/TFusion#pretrain). You need to pretrain before evaluation and transfering. So please check it.

What's more, when you run transfer.py and failed to generate `renew_ac.log`, there must be some errors or warnings around `os.system` execution. Please pay attention to these hints and paste it here, that's most important issues for us to help you find out what happened.

**Comment by qqzhao93** [comment]
pretain部分的工作都做了，https://github.com/qqzhao93/image/blob/master/pretrain.png
transfer部分的代码本身没有报错和警告，断点调试到os.system那一行代码的时候，进入不了rank_reid.py函数，直接跳出到return语句，https://github.com/qqzhao93/image/transfer_1-3
rank_reid.py部分的代码如下两图，sys.argv[0-2]分别对应transfer.py中调用rank_reid函数的三个部分，但是sys.argv的其他参数定义是在哪的？

**Comment by ahangchen** [comment]
Most of the links about the images are 404 not found. Please have a look at your comment and make sure them work after you post the comment. They are modifiable.

If you want to show me the code you modified, you can fork the project and refer the code with url. Snapshots are hard to read and understand. I suggest you not to use this form any more... 

I search in your [snapshot project](https://github.com/qqzhao93/image) and got these:

- You pretrain the models correctly.
- You are debugging in TrackViz, thus it's impossible to jump into a breakpoint in rank-reid. Because from TrackViz to rank-reid, we use `os.system`, which is a inter process call. If you want to view what happened in rank-reid, you can paste the console output when you run `os.system` in TrackViz. Otherwise you need to debug in rank-reid/rank_reid.py, passing command line arguments as TrackViz project did. I think that's some basic knowledge about python programing, so I won't speak more about this.

What matters is the errors when you run 

```python
os.system('/home/ubuntu/anaconda2/bin/python /home/ubuntu/coding/rank-reid/rank_reid.py 0 '
+ source + ' ' + target + ' '
+ vision_train_rank_pids_path + ' '
+ vision_train_rank_scores_path + ' '
+ vision_test_rank_pids_path + ' '
+ vision_test_rank_scores_path)
```

(I have figured this out in the previous response). I can not find any infomations about this in your project(There may be some clues in the front of your current position in the console. That's basic knowledges too. I won't repeat it). If you came across some errors in the console output when you run this line, please directly paste them here, rather than anything else. This is the easiest way to save our time.
